
[build]
    functions = "functions"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "https://portfolios-project-server.netlify.app/.netlify/functions/api/:splat"
  status = 200
